### ISSUE TITLE
/account/ "My Details" Full Name

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#39]
Full name is not updating the full_name table.

**Comment by jaredhwlt** [comment]
So you mean it isn't updating Stripe or Customer.io?

**Comment by whaleen** [comment]
https://www.loom.com/share/d9ee9c0dd48e45ebb6856664aab76556?sid=9269bb7b-63d5-4f16-a711-34ded9bea79b

**Comment by whaleen** [comment]
@jaredhwlt  I'll take care of this one

**Comment by whaleen** [comment]
Some comments on the First Name and Last Name capture we are doing in the Subscribe flow:

https://www.loom.com/share/d779b90baea24bfeac379333e126d374?sid=c616f992-8968-4485-b7af-684c056b1932
