### ISSUE TITLE
/account "Email Preferences" 

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#41]
https://www.loom.com/share/f4413c7903b74033bc718a7da6e33c4c?sid=9858194f-fe2d-4e6a-9592-4954fa1025af

**Comment by jaredhwlt** [comment]
https://github.com/Pirate-Wires/pirate-wires/commit/af61abb7d7ef4ecad46b2cf356f53e6c0cf84c34
I fixed the issue and seems like everything works well.
