### ISSUE TITLE
Payload from `newsletterCallout.tsx` appears to not respect existing prefs and will overwite

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#42]
https://www.loom.com/share/d36f5191bfd848b99e5c77485c3badd3?sid=5a80d420-7a3c-4463-a25f-a9d374e97f55

**Comment by whaleen** [comment]
Testing/discussing the individual page (wp, wires, industry) call outs: https://www.loom.com/share/2fc32e142bca4d988cfbdcdadae64413?sid=63c9a09c-5976-4771-a522-a10c832f6922

**Comment by jaredhwlt** [comment]
https://github.com/Pirate-Wires/pirate-wires/commit/77ad9795860f215f413b23ccb2d24200c87208ee
I've fixed preference overwriting in newsletter cta.
will close the issue.
