### ISSUE TITLE
Subscribe flow for authenticated users

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#52]
https://github.com/Pirate-Wires/pirate-wires/commit/af10d19c2268d090a51bde472a461946bcd81537

- [x] #53
if email (has account) recognized, issue OTP and continue as normal

- [x] #54
if session, pre-fill email and hide name fields,  bypass OTP and continue as normal

- [x]  No account 
subscribe flow works as desired in this case.

**Comment by whaleen** [comment]
The Subscribe flow obviously onboards new users as expected. 

But, we need to be sure it handles all existing users. This addresses people who have either:
1. abandoned the process at an earlier time and therefore have an account but are not a paid subscriber and so we want them to pick up where they left off and pay for a subscription.
2. they have subscribed to a newsletter and therefore have an account, but like the first case the subscribe flow will handle them in the same way.

**Comment by jaredhwlt** [comment]
https://github.com/Pirate-Wires/pirate-wires/commit/333af0c94076c03f1eb23872401e0a593d124d50
Fix the issue.
