### ISSUE TITLE
Auth states snippet

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#74]
point @joshkirk to example where an authenticated user is subscribed or not to help show the right ui elements 

```
if auth
  use user object
if subscribed
  use subscribed status
...
```

showing the appropriate content to users who are logged in as well as an additional layer of content to users who have a paid subscription.

**Comment by whaleen** [comment]
The `featuredNesletters` per each vertical page should
1. reject an already existing subscription to that “vertical” as it is doing now
2. but also, for the authenticated user who is know to be subscribed to that particular “vertical” show an alternate peace of html (to be determined later)

The `newsletters` page should be hidden from navigation for authenticated users as we will show instead the `account` page link in place of both `sign-in` and `newsletters` links.

The `Subscribe` link should only be shown to un-authenticated users AND authenticated users who are not yet paid subscribers.

**Comment by jaredhwlt** [comment]
https://github.com/Pirate-Wires/pirate-wires/commit/c41e3e93bcbef4dac060a44733c2917f846bf67a
I fixed navbar items for authenticated users.

**Comment by whaleen** [comment]
@jaredhwlt 

> Hey 
> [@Josh Vaage](https://josh-lwj4813.slack.com/team/U05MG5ZHZH8)
>  how come there are two user functions, the one you mentioned in MegaNav, const { session, user: userDetails } = useSupabase();
> And one in the comments area that it looks like Jared added called const { user, profile } = useUser();
> When I check the value that useUser() returns, it says I'm not logged in even though I am and the meganav reflects that.
