### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by whaleen** [Pirate-Wires/pirate-wires#75]
Identify which processes are automatic, and which are manual and prepare accordingly for going live. Set documented routines where needed if we must continue any manual syncs.

**Comment by jaredhwlt** [comment]
https://github.com/Pirate-Wires/pirate-wires/commit/d53a9bd0f356b41ec53b72dd1dc614910130e234
I've added sync our three dbs - supabase, stripe and customer.io. It's for syncing existing ones and after you can run `pnpm run sync`, there aren't any orphaned users in three dbs.
